
extern crate bytes;


pub trait MsgShape<T> {
    const ENCODED_LEN: usize;
    const MSG_HASH_CODE: u16;
}
//#[derive(Debug, PartialEq, Clone, Default)]
//pub struct UorbMessage {
//    pub hash: u32,
//    pub name: String,
//    pub description: Option<String>,
//    pub fields: Vec<Uorb>,
//}

//pub trait SerializationPair {
//    fn deser(input: &[u8]) -> Option<Self>;
//    fn ser(&self) -> Vec<u8>;
//}

// import code generated by parser at build time
pub mod common {
    use bytes::{Buf, BufMut, Bytes, IntoBuf};

    include!(concat!(env!("OUT_DIR"), "/common.rs"));
}



#[derive(Debug, Clone)]
pub struct UorbHeader {
    pub version: u8,
    /// unique hash of the msg name
    pub hash: u16,
    /// the "instance" of the sensor/entity that sent this
    pub instance_id: u8,
    /// length of the payload in bytes
    pub payload_len: u16,
}





/// Utilities for sending and receiving uORB via a reliable transport
pub mod wireline {
/*
HOWTO transmit/receive uORB
    _sendbuf[0] = (hash_val >> 8) & 0xFF;
    _sendbuf[1] = hash_val & 0xFF;
    _sendbuf[2] = instance_id; //the "instance" of the sensor /entity that sent this
    _sendbuf[3] = (payload_len >> 8) & 0xFF;
    _sendbuf[4] = payload_len & 0xFF;
    followed by payload data...
*/

}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }



}
