

// import code generated by parser at build time
pub mod common {
    include!(concat!(env!("OUT_DIR"), "/common.rs"));
}


#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }



}
